name: Build

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: kgrubb/build-action@master
      with:
        dependencies: "libgtk-3-dev"
      env:
        DESTDIR: out
  lint:
    runs-on: ubuntu-latest
    container:
      image: valalang/lint
    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: io.elementary.vala-lint
