name: CI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: elementary/docker:unstable
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y meson libgtk-3-dev valac
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build
        ninja -C build install
  lint:
    runs-on: ubuntu-latest
    container:
      image: valalang/lint
    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: io.elementary.vala-lint

on:
  push:
    branches:
      - master
 release:
    runs-on: ubuntu-latest
    container:
      image: madisongrubb/release
    steps:
    - uses: actions/checkout@v1
    - name: Publish Release & Generate Changelogs
      run: elementary-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_USER: "${{ secrets.GIT_USER }}"
        GIT_EMAIL: "${{ secrets.GIT_EMAIL }}"
        GIT_KEY: "${{ secrets.GIT_KEY }}"