name: Release
on:
  pull_request:
    types: closed
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'release'
    steps:
    - uses: actions/checkout@master
    - uses: kgrubb/release-action@master
      if: github.event.pull_request.merged == true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}