name: Release
on:
  pull_request:
    branches: master
    types: closed
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && true == contains(join(github.event.pull_request.labels.*.name), 'release')
    steps:
    - uses: actions/checkout@v1
    - name: Create release
      uses: kgrubb/release-action@master
      env:
        GIT_USER_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
        GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      with:
        release_branch: 'juno'