name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: madisongrubb/release
    steps:
    - uses: actions/checkout@master
    - name: Publish Release & Generate Changelogs
      run: elementary-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
