name: Release
on:
  pull_request:
    types: closed
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: kgrubb/release-action@master
      if: github.event.pull_request.merged == true && github.event.pull_request.labels.includes('release')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}